Add Component, Assignment, Exam, ClassParticipation
AY2425S1-CS2113-W13-4/tp pull request #49
Opened 2024-10-19 09:48 UTC by TrungBui32

Add abstract class Component and its children: Assignment, Exam, ClassParticipation
Solve issues #48

2024-10-19 10:04 UTC, ThienDuc3112 commented
Please change UML to reflect the now abstract class Component

Other than that, LGTM

2024-10-19 10:24 UTC, ThienDuc3112 commented
Should Override equals and toString in each of the child class and the component class as well, you can update the UML to reflect that

the rest LGTM

2024-10-19 10:24 UTC, ThienDuc3112 requested changes
Needed to add equals and toString method

2024-10-19 14:07 UTC, ThienDuc3112 approved these changes
LGTM, just need to make it pass the code style check

2024-10-20 13:21 UTC, RCPilot1604 approved these changes
Looks good to me

2024-10-20 13:21 UTC, RCPilot1604 commented on src/main/java/tutorlink/componentpackage/Exam.java
> +        return "Exam " + super.toString();
Maybe for this you would want to include some formatting to make it clear that "Exam" is the description (component) and the following string is the name: 

Eg. "Exam: CS2113 finals"

2024-10-20 13:25 UTC, jinzihan2002 approved these changes
LGTM

2024-10-20 13:56 UTC, merged