Add Grade
AY2425S1-CS2113-W13-4/tp pull request #55
Opened 2024-10-22 12:21 UTC by TrungBui32

Add Grade
Solve #46

2024-10-22 13:37 UTC, RCPilot1604 requested changes

2024-10-22 13:37 UTC, RCPilot1604 commented on src/main/java/tutorlink/grade/Grade.java
> +            return this.score == grade.score
I think we shouldn't be checking for the equivalence of score because even if the scores are different as long as the component and the student is the same, we should throw an exception (duplicate Grade object). 

Unless we want to implement the functionality where it overrides the existing Grade object with one with a new score?

2024-10-22 13:46 UTC, RCPilot1604 requested changes

2024-10-22 13:46 UTC, RCPilot1604 commented on src/main/java/tutorlink/grade/Grade.java
> +
Additionally, could you implement getGradeMatricNumber(): String and getGradeComponentDescription(): String as I am unable to use the .equals() override in Grade as I cannot instantiate an instance of the Component abstract class. Thanks!

2024-10-22 13:50 UTC, RCPilot1604 requested changes

2024-10-22 13:50 UTC, RCPilot1604 commented on src/main/java/tutorlink/grade/Grade.java
> +            return this.score == grade.score
You may need to cast obj to Student

2024-10-22 15:34 UTC, ThienDuc3112 commented on src/main/java/tutorlink/grade/Grade.java
> +            return this.score == grade.score
equals shouldn't return exception, though we can make a separate function to check if it's same component same student but different score

2024-10-22 15:37 UTC, ThienDuc3112 requested changes

2024-10-22 15:37 UTC, ThienDuc3112 commented on src/main/java/tutorlink/grade/Grade.java
> +            return this.score == grade.score
no need to cast obj student as casting grade implicitly mean student of grade is of type Student

2024-10-22 15:37 UTC, ThienDuc3112 commented on src/main/java/tutorlink/grade/Grade.java
> +    }
too specific, return Student and Component would be better
replace getGradeMatricNumber -> getStudent
replace getGradeComponentDescription -> getComponent
both or just simple getter

2024-10-22 15:52 UTC, ThienDuc3112 approved these changes
LGTM

2024-10-23 01:14 UTC, RCPilot1604 approved these changes
LGTM

2024-10-23 01:14 UTC, merged